version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/proteinus
    tty: true
    environment:
      - WATCHPACK_POLLING=true
    command: yarn dev
