# [Choice] Node.js version (use -bullseye variants on local arm64/Apple Silicon): 18, 16, 14, 18-bullseye, 16-bullseye, 14-bullseye, 18-buster, 16-buster, 14-buster
ARG VARIANT=18-bullseye
FROM node:${VARIANT}

ENV IMAGE_VARIANT="18-bullseye"

WORKDIR /workspaces/proteinuslp
RUN useradd --create-home --shell /bin/bash vscode

RUN chown vscode:vscode -R /workspaces /usr/local

COPY . .

RUN yarn install